#!/bin/sh

tf_env=$HOME/tensorflow_env

if [ ! -d $tf_env ]; then
  # create a virtual environment for TensorFlow
  python3 -m venv --system-site-packages $tf_env
  source $tf_env/bin/activate

  printf '\nUpgrading pip...\n'
  pip install --upgrade pip

  printf '\nInstalling TensorFlow...\n'
  pip install --upgrade tensorflow

  # deactivate the environment
  deactivate
fi
