#!/bin/sh

if [ $(uname -s) = Linux ]; then
  printf '\nUpgrading packages...\n'
  sudo apt update
  sudo apt upgrade

  if [ -z $(command -v zsh) ]; then
    printf '\nInstalling zsh...\n'
    sudo apt install zsh
  fi
fi

case $SHELL in
  *zsh)
    ;;

  *)
    printf '\nChanging shell to zsh...\n'
    sudo usermod -s $(which zsh) $USER
    sudo su - $USER
    ;;
esac

# set proxy variables
source $HOME/.zshenv
