#!/bin/sh

if [ $(uname -s) = Linux ]; then
  echo -e '\nUpgrading packages...\n'
  sudo apt update
  sudo apt upgrade

  if [ -z $(command -v zsh) ]; then
    echo -e '\nInstalling zsh...\n'
    sudo apt install zsh
  fi
fi

case $SHELL in
  *zsh )
    ;;

  * )
    echo -e '\nChanging shell to zsh...\n'
    sudo usermod -s $(which zsh) $USER
    sudo su - $USER
    ;;
esac

# set proxy variables
source $HOME/.zshenv
